[general]
bars = 20
framerate = 18
sleep_timer = 0

[input]
method = pulse
source = easyeffects_sink.monitor

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 90
bar_delimiter = 59
frame_delimiter = 10

[smoothing]
noise_reduction = 30